# Generated by Django 5.1.6 on 2025-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
