# Generated by Django 5.1.6 on 2025-02-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramuser_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='full_name',
        ),
    ]
